sass:
  style: compressed

#gauges_id:
#google_analytics_id:
#google_site_verification:

#repository: 

timezone: Asia/Ho_Chi_Minh

defaults:
  -
    scope:
      path: "_product"
      type: "product"
    values:
      layout: "product"
  -
    scope:
      path: "_posts"
      type: "posts"
    values: 
      layout: "news_item"
  -
    scope:
      path: "_show"
      type: "show"
    values:
      layout: "show"

collections:
  product:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  show:
    permalink: /:collections/:path/
    output: true

name: Triet ly lan da • Skinlosophy
description: Triet ly lan da
url: https://trietlylanda.github.io

#logo: img/logo-2x.png

#plugins:

exclude:
  - .gitingore
  - CNAME
  - readme.md
